# Generated by Django 4.2 on 2023-04-10 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_date_created_newsarticle_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='users_added',
            field=models.ManyToManyField(blank=True, related_name='articles_to_read', to=settings.AUTH_USER_MODEL),
        ),
    ]
