# Generated by Django 4.2 on 2023-04-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_coinamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinamount',
            name='change_percent_24hr',
            field=models.DecimalField(decimal_places=2, default=-1234, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coinamount',
            name='price_usd',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=19),
            preserve_default=False,
        ),
    ]
